# Generated by Django 4.2.7 on 2025-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_seat_payment_alter_seat_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='payment',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
